@baseUrl = bedplas.be
@token = eyJ1c2VyX2lkIjoxLCJ0b2tlbl92ZXJzaW9uIjoyfQ.ajLsHQ.GIun7o5wJQJeWMLZuvPnKyoA_vU

GET {{baseUrl}}/api/health

###

POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "demo",
    "email": "demo@example.com",
    "password": "ChangeMe123!"
}

###

POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "identifier": "admin",
    "password": "Stationsstraat113"
}

###

GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/api/example
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "sample",
    "description": "example row"
}

###

POST {{baseUrl}}/api/addParticipant
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Sam",
    "last_name": "Vandenabeele",
    "phone_1": "+32465094556"
}

###

POST {{baseUrl}}/api/graphData
Content-Type: application/json

{
    "participant_id": 1
}